{% set name = "pathable" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p1c2u/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: a11fab524f653bb4cabe4cb06a0accbe115db8a02cdb3153a608d1dd9a56a373

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pathable
  requires:
    - pip
    - pytest-cov
  commands:
    - pip check
    - pytest tests -v

about:
  home: https://github.com/p1c2u/pathable
  summary: Object-oriented paths
  description: Object-oriented paths
  dev_url: https://github.com/p1c2u/pathable
  doc_url: https://github.com/p1c2u/pathable
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl