{% set version = "0.4.2" %}

package:
  name: pathable
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pathable/pathable-{{ version }}.tar.gz
    sha256: c3958c73d43c26ab7f5bc0795e1b8f342b77746a887a2245b1469181531a4d59
  - folder: src
    url: https://github.com/p1c2u/pathable/archive/refs/tags/{{ version }}.tar.gz
    sha256: 67af77b18e386f93b550b64cdeabfb43290766852ceed1b7c5a439f2ef3869e8

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  source_files:
    - src/tests
  imports:
    - pathable
  commands:
    - pip check
    - pytest src/tests -vv --cov=pathable --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=79
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/p1c2u/pathable
  summary: Object-oriented paths
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
