{% set version = "0.4.1" %}

package:
  name: pathable
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pathable/pathable-{{ version }}.tar.gz
    sha256: a6c9404550b6fff15bc95dadb0bfd07d7d0e0f178b7d300ca847bf288aa87fb7
  - folder: src
    url: https://github.com/p1c2u/pathable/archive/refs/tags/{{ version }}.tar.gz
    sha256: 2c2cd4fc8aa29dd9b956229e7aed78d2ea5b5869525806f7bd60dbe0176a197b

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  source_files:
    - src/tests
  imports:
    - pathable
  commands:
    - pip check
    - pytest src/tests -vv --cov=pathable --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=79
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/p1c2u/pathable
  summary: Object-oriented paths
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
